name: animations
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  go_router: ^16.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

# top-level configuration for launcher icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
